server.port: 8080
spring.mvc.pathmatch.matching-strategy: ant_path_matcher

spring.h2.console.enabled: true
spring.datasource.url: jdbc:h2:mem:test
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: admin
spring.datasource.password: admin
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

twitter:
  cron:
    seconds: 30
  query-count: 100
  min-followers: 1500
  min-hashtagcount: 10
  languages:
    - es
    - fr
    - it
  users-to-search:
    - lemonde
    - elmundo
    - theguardian
    - NewIzvestiya
    - elpais
    - lejournal
    - larepubblica
    - lib√©ration
    - CNN
    - lavanguardia